# Generated by Django 5.0.3 on 2024-06-06 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_file_transfer', '0004_blockchain_alter_fileupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='user',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to='secure_file_transfer.user'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='sender',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='sent_files', to='secure_file_transfer.user'),
            preserve_default=False,
        ),
    ]
