# Generated by Django 5.0.3 on 2024-06-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_file_transfer', '0005_remove_fileupload_user_fileupload_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='encryption_key',
            field=models.CharField(default=3, max_length=44),
            preserve_default=False,
        ),
    ]
