# Generated by Django 5.0.6 on 2024-06-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_file_transfer', '0006_fileupload_encryption_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='nonce',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
