# Generated by Django 5.0.6 on 2024-06-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_file_transfer', '0010_alter_wallet_balance_alter_wallet_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='ipfs_hash',
            field=models.CharField(default=11, max_length=46),
            preserve_default=False,
        ),
    ]
