# Generated by Django 5.0.6 on 2024-06-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_file_transfer', '0014_alter_fileupload_encryption_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='original_filename',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
